# Generated by Django 2.2.6 on 2019-11-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_auto_20191030_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
        ),
    ]
