# Generated by Django 2.2.6 on 2020-01-08 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_auto_20200108_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishimage',
            options={'verbose_name': 'Фотография еды', 'verbose_name_plural': 'Фотографии еды'},
        ),
        migrations.AddField(
            model_name='drink',
            name='short_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='DrinkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='drink_images/')),
                ('drink', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.Drink')),
            ],
            options={
                'verbose_name': 'Фотография напитка',
                'verbose_name_plural': 'Фотографии напитков',
            },
        ),
    ]
