# Generated by Django 2.2.6 on 2019-11-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_sortdish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortdish',
            name='sort',
            field=models.CharField(choices=[('sort price', 'price'), ('sort name', 'name')], default='price', max_length=15),
        ),
    ]
