# Generated by Django 2.2.6 on 2020-01-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_auto_20200108_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
