# Generated by Django 2.2.6 on 2019-11-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_auto_20191117_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortdish',
            name='sort',
            field=models.CharField(choices=[('price', 'sort price'), ('name', 'sort name')], default='price', max_length=15),
        ),
    ]
