# Generated by Django 2.2.6 on 2020-01-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0008_auto_20200108_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
