# Generated by Django 2.2.6 on 2019-11-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191112_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='74fc18217bd4400ab109463f865c1529826bc6eb161447de8d3f112254c1918f', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='38facfa16e5b41c582f82b239d4f6d0c3a3e510a004c46fab286895150b89b77', max_length=300, null=True),
        ),
    ]
