# Generated by Django 2.2.6 on 2019-11-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191116_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='1b54ce69b1ff444fafe7839fb47dc4a3eb24d7ac046b4658bb28fa7396229433', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='3de90c6a38a04768aa2dc786a85e27ba1d2e854e84fd4223a4fb2525e38755d4', max_length=300, null=True),
        ),
    ]
