# Generated by Django 2.2.6 on 2019-11-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191114_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='0bfe1223da31483ca0caa03d2d7e7598d249cde6f8ed45dfbd950fb433f009d4', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='6e77cb98dbac40b6b148206fba5cf40b283ea0e34dd14235b7ba2cbd23dc3585', max_length=300, null=True),
        ),
    ]
