# Generated by Django 2.2.6 on 2019-11-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191116_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='5a26c9b90bea481b91756e594e8c742e5f4fc617317d44418266b8e69aee8c70', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='8b83b7b382c143609c56043a731c50396246fef2d0a54fef915caf80e50eafb0', max_length=300, null=True),
        ),
    ]
