# Generated by Django 2.2.6 on 2019-11-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191117_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='7f42685dc1454144982008e12fb0e98ce2a3cff0a5cf4767b3192e3670411c16', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='edd570cc99c742238d39f768c528db7257074af94f4b4fe38df75a6be13cb23d', max_length=300, null=True),
        ),
    ]
