# Generated by Django 2.2.6 on 2019-11-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191117_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='5fff8fe205fa44cca077a795334f1fafbdff581c4fe74bc7bc2bc2e3653c7de2', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='be7553de75be4aa8866585073fa068399a6ff3ae3a2842409af0901fac983e07', max_length=300, null=True),
        ),
    ]
