# Generated by Django 2.2.6 on 2019-11-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191117_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='6f976f66037e4b3989f971d97f0b87d417c448c23cf54e38a2ea09b7b62482f1', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='0e5545eec19645a3b2a0413cd9528a65580558cb9a414b1eb332551e7be1fbfa', max_length=300, null=True),
        ),
    ]
