# Generated by Django 2.2.6 on 2019-11-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191117_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='ae525155a5c34f7dac064070dc7be31c8f4f06b7e9b4455f9c042d4f35ad20d6', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='ca8a275650bc421bba8dbcfef07a23598de1e6cdd0a34cd6bace83e57af5738d', max_length=300, null=True),
        ),
    ]
