# Generated by Django 2.2.6 on 2019-11-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20191117_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='d87bda17c86148009b8f5332c940a24d8c8564aaf216485c9672d601dc63c525', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='1713c1a2633948729b81f7dfd563a082c9e319d1791e4bae90fa7ba03a551b17', max_length=300, null=True),
        ),
    ]
