# Generated by Django 2.2.6 on 2019-11-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20191117_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='945ca8ff2dfe4dcf95129149e71af083b27c5da0f41e453ab545791f9bc71170', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='b9d7c3add2eb492fabf400f2cbdba3537b248a8d506e4cba90e25a2a92001847', max_length=300, null=True),
        ),
    ]
