# Generated by Django 2.2.6 on 2019-11-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20191117_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='f6023d3858f14313bfd824c8dd70738957936b9771b74fdb8fdf7091a6934fb4', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='973ee69cabf0416dbf5c0f56d2d02e8916a4597bc6de444bb5869818c75d25ee', max_length=300, null=True),
        ),
    ]
