# Generated by Django 2.2.6 on 2019-11-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20191118_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='7a6de8e2d16c4231851517864aed8de53200e00dc82a47ca9c63b81f6fda5145', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='16265ce06cc54066a9440af5fdedb0ee17c571025d504ba18012492e91b253d7', max_length=300, null=True),
        ),
    ]
