# Generated by Django 2.2.6 on 2019-11-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20191118_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='08a3a206a769409e871225aefe7eafdde4953553743c477cb0e2004f8416dc22', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='aa699acbca124c268439a62b326a2657930d50363cda440398f99e3dfbc73783', max_length=300, null=True),
        ),
    ]
