# Generated by Django 2.2.6 on 2019-11-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20191118_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='8d9541b6d0cf49148695670f60c0513ad0c9a25e012f4b0a8077b8ec95606ef5', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='2409b2baaba946ae8af4900da5cc581f00d4b5a7e39e4262ab5316175377e1de', max_length=300, null=True),
        ),
    ]
