# Generated by Django 2.2.6 on 2019-11-23 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20191118_0108'),
        ('accounts', '0007_auto_20191114_0242'),
    ]

    operations = [
    ]
