# Generated by Django 2.2.6 on 2019-11-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20191118_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='b379584feb8b4325b9ec547c8dbcb33d26e62a473710490ab9f5a13f3b8825d4', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='b4822c29afcd4a748edd6309eb95803e9fa1e7be00bd4c3c98005fb619f163af', max_length=300, null=True),
        ),
    ]
