# Generated by Django 2.2.6 on 2019-11-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_merge_20191124_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='70635c5cacc645f18c58b4ecba967c9c0956c4f5bf7c4e64ab339eb3192cebde', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='73eae11d345b482a99772c36969afb19466d38ffd74945d592f605467e256669', max_length=300, null=True),
        ),
    ]
