# Generated by Django 2.2.6 on 2019-11-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20191121_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='faec9f6e22974c90851dc101a05c51b244d34da1816e4c8981b03986f26919a6', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='56117df7cdd34f7e8370fabf7605e064ee584c1f1df7496397ac81d8366683ab', max_length=300, null=True),
        ),
    ]
