# Generated by Django 2.2.6 on 2019-11-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20191121_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='71bec605160a48b28484988e351699870e33cf44107047d1a555b28131b3c9a6', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='cb0ae266339c47d3a007540535568ebc02f30a4bba7c462f8ac09157b1ce4a0f', max_length=300, null=True),
        ),
    ]
