# Generated by Django 2.2.6 on 2019-11-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20191124_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='51f686c7c6b643b9b2af0bfa78596263491513f4b71e49b9a903bda80ac7fd6c', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='4d2c6724d804442d9b3d3c5be0e645f045578cfb6c134a1cad2c77c31db5f930', max_length=300, null=True),
        ),
    ]
