# Generated by Django 2.2.6 on 2019-11-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20191124_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='70ce542c51264b9b82d2139148882a001fe71154b3f44bbcad1cc19bcb1e9239', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='17e21e9ece784ed38c186ee4a155c0c47e55205cb0ac46a784cdf01154936ebe', max_length=300, null=True),
        ),
    ]
