# Generated by Django 2.2.6 on 2019-11-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20191124_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='4d7977b38d5842b1b62accc3b0a810bf06887af45ddb4e64bd0e0eda1a5b6f30', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='05977ac3228e428d8ecf9c8d0e5299062eaf8bddb0e84ea5990fdfbdcd654fcf', max_length=300, null=True),
        ),
    ]
