# Generated by Django 2.2.6 on 2019-11-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20191124_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='bc8b476756764bc1b1e8db1c8f06c1d51487c5f426d140658e159b12e0f823bd', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='e6a6fe3546f849e880aecabcbdd58d20a0cd8cc5a81648429bc2c8bbc6c1266e', max_length=300, null=True),
        ),
    ]
