# Generated by Django 2.2.6 on 2019-11-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20191124_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='9bd25779018e439cb1d166f11d66fdcf47e24c33031245d39dd99cf4d1270381', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='db5b2c9a05ce49f59a381d2ae09bb2a3889308584e6a44079b7a48166a2bd9ce', max_length=300, null=True),
        ),
    ]
