# Generated by Django 2.2.6 on 2019-11-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20191124_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='f07e840d909c4b0fa4c4b5ccfd2b7365cdd60b366f814c4f8555bf0eeddb8d64', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='1fd7ff07e760437fa1aac1af9a5baedc0d0568de468b49359342b52b87472155', max_length=300, null=True),
        ),
    ]
