# Generated by Django 2.2.6 on 2019-11-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20191124_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='c164c6b178464107b6fd98d663d5d44935662cc6cf5e4ed5bf0e66e407527240', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='03d680d30ec04b76abd7ea11b5a93537a4fe592cc0aa43b28ac4c9498767fc38', max_length=300, null=True),
        ),
    ]
