# Generated by Django 2.2.6 on 2019-11-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20191125_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='ca66c3e412ab4a79b61f565e317db49e374085e1b0304414950656725b621592', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='8fe6c4c8429f4044ae25ce6f8b58ae20421c55535068419a90bfdab991e6c5c6', max_length=300, null=True),
        ),
    ]
