# Generated by Django 2.2.6 on 2019-11-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20191125_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='3be11df8bc7f4f51affef36145a5d866b267db66b0374bdc83ad48987ecf1e6d', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='a89a3153ec6e45ec9574cad29c5d7fab873e7715e20e4abc838993cb97f35014', max_length=300, null=True),
        ),
    ]
