# Generated by Django 2.2.6 on 2019-12-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20191201_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='9f29b0741a834384ba0896b4d48efb463abbf8fec7c646bea6dfc259e01d56be', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='512875276508481c9ad26a044ba75c959f5f8b99012346759c2b05f2d27f932c', max_length=300, null=True),
        ),
    ]
