# Generated by Django 2.2.6 on 2019-12-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20191201_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='dce9944b3f124693ba8bc903ad2efd6eb2bb65640195428291a9ad8bd55ca6af', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='5075402d18b440a6afaafe69d02f0cbcc5dc0801b88e46be92d0ef07e841f4de', max_length=300, null=True),
        ),
    ]
