# Generated by Django 2.2.6 on 2019-12-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20191202_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='2473c497003c4bfdaf953cdcce6c8461ade59d0801ba40ce8943be1c9464e593', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='cdc1aba7281849769a9d5caf6b1571ce115626c8d36b47d2b3b7b5e807888413', max_length=300, null=True),
        ),
    ]
