# Generated by Django 2.2.6 on 2019-12-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20191202_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='195bdb2bc53a4da6980ec2d6ebf56c0c331ffdb5c43d4c7b92acd971cbf3d5e9', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='06016ed095d14734b681d879ab1db09710a7a42b7cee4d359d8d5da6d469871b', max_length=300, null=True),
        ),
    ]
