# Generated by Django 2.2.6 on 2019-12-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20191202_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='f7f7ecc8648f4b1eb006d8e0220fd1d15788738f23164ac1a6b7f43970a22cd8', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='30ef58164b444043bdf74a296d0aab79d5599d9c5e644c0aadb84ab313e598bb', max_length=300, null=True),
        ),
    ]
