# Generated by Django 2.2.6 on 2019-12-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20191202_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='2f442109a7da406e93eaccbc4f7bba086c8d73fb590044c2a63e5e7103e6674b', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='820743170d04435fa0c441638de43410cdd78bafd5f94e4dbe7d0e9c6bf8eb1c', max_length=300, null=True),
        ),
    ]
