# Generated by Django 2.2.6 on 2019-12-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20191202_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='8baee98f267245b18692ac259f01eac92f6b48e0e8b14fdeaf5300bfc7e8532d', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='090687649367446fa54bbd21ef5633e06b310dd42d8843e79871480b450a6054', max_length=300, null=True),
        ),
    ]
