# Generated by Django 2.2.6 on 2019-12-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20191202_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='02ea91e33bbb45ebbfba1b487668993bff607c698620418a9fe56456cec7551a', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='014c979845c64e1889a338ec7fed5d853e3cee6452d54748ad9718e73efcbe31', max_length=300, null=True),
        ),
    ]
