# Generated by Django 2.2.6 on 2019-12-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_auto_20191214_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='b8858411f090494abe33e0ac0bfa100e89aea3c5684a4e5e9e89e646a2c89420', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='016cce2f31e941f7baecda05194158248ec8ff9c9f194dbba6c1638179c7b029', max_length=300, null=True),
        ),
    ]
