# Generated by Django 2.2.6 on 2019-12-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_auto_20191215_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='1341ddb6cc7d47edaf8c8dfe2a16a4e95ba20bcb187d462abb86dc6e6f07a696', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='f8630b0b718f4c38b0f1a8697f002be36ef8f689576a437ba1a218fac838a914', max_length=300, null=True),
        ),
    ]
