# Generated by Django 2.2.6 on 2019-12-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20191215_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='b1e8bc12f7474d4e9299d3d859edd5f23832134a5b1b466aae523bbb26525e06', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='79d457eaeb8d4b15ba91f5c42baa4250207a96493cb2449ba1ac96f1f3f84d64', max_length=300, null=True),
        ),
    ]
