# Generated by Django 2.2.6 on 2019-12-26 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20191124_0105'),
        ('accounts', '0057_auto_20191216_2359'),
    ]

    operations = [
    ]
