# Generated by Django 2.2.6 on 2019-12-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_auto_20191227_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='52dbf0c2360f4d3c8751146117c35ab3df1ef8c4bf3c42cf88b4b0797c3d3df1', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='a9c1ad30dc3340fb96cf027f15a5d3e9e750ce68ca3b4576b013ac8142d8f5e5', max_length=300, null=True),
        ),
    ]
