# Generated by Django 2.2.6 on 2020-01-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_auto_20191230_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='7fffbcfb046844949cb2c1507ccf01197e16d3df9c8448e9a230123c37b19927', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='d50cd48865d14d0c9197c1a2e6018eeeb0c36488a109457a8de93c86fe789b71', max_length=300, null=True),
        ),
    ]
