# Generated by Django 2.2.6 on 2020-01-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_auto_20200104_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='ed02353e360b40f8be08544fd45b230f0717161d5d7341d1a2b1e8ed8c4c0937', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='a604f08c7528463aa1d6f43769d68ef470b0229d53154d31a8224eac1c711a8d', max_length=300, null=True),
        ),
    ]
