# Generated by Django 2.2.6 on 2020-01-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_auto_20200104_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='719dd6b0247d4e62a91a3ee4b046af26992b9778238d497094fcbde15740df05', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='bfaece12b8aa4de49d2f3637de01f5cdcd8982b719b240e5af9f4aba77d0ff8f', max_length=300, null=True),
        ),
    ]
