# Generated by Django 2.2.6 on 2020-01-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_auto_20200108_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='e1cc03cb494e4e9db6b40a5cac315e2394cfc454245e48c0ac812540dad83d1f', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='57e5b23a607e4ae7b7f3eb8c941d41d63a98216fbd3a4c5180daae6eee89afaa', max_length=300, null=True),
        ),
    ]
