# Generated by Django 2.2.6 on 2020-01-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('delivery', models.CharField(choices=[('not_delivery', 'Самовывоз'), ('delivery', 'Доставка по адресу')], default='Доставка по адресу', max_length=15)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('comment', models.CharField(max_length=500)),
                ('payment_choice', models.CharField(choices=[('cash', 'наличными'), ('card', 'картой')], default='наличными', max_length=15)),
            ],
        ),
    ]
