# Generated by Django 2.2.6 on 2020-01-18 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200113_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order'),
        ),
    ]
